### PR TITLE
fix(addApplicationsModal)add new text to add modal #651

### PR DESCRIPTION
**Pull request by SOAP1914**
Remove Webtop-disabled apps from Webtop add modal

### CODE REVIEW

**Comment by SOAP1914** [comment]
@wski @clarkjefcoat

**Comment by clarkjefcoat** [comment]
:-1:?  I don't believe we have the necessary backend changes implemented for this to be an accurate message.  Please wait before merging.

**Comment by SOAP1914** [comment]
ok np @clarkjefcoat thanks

**Comment by tonyalletag** [comment]
Dependent on ozp-backend issue [#102](https://github.com/ozone-development/ozp-backend/issues/102)

**Comment by tonyalletag** [comment]
:+1: Front end changes good to go once connected to new API call

**Pull request closed without merging**
